services:
  dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    volumes:
      - ..:/workspaces/sieve:cached
    command: sleep infinity

  websieve:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      SIEVE_LOG_LEVEL: debug
      DOVECOT_HOST: dovecot
      DOVECOT_PORT: "4190"
      AUTH_USER: user
      SSL_CERTIFICATE_FILE: ${SSL_CERTIFICATE_FILE:-/etc/ssl/certs/fullchain.pem}
      SSL_CERTIFICATE_KEY_FILE: ${SSL_CERTIFICATE_KEY_FILE:-/etc/ssl/certs/privkey.pem}
    ports:
      - "8080:80"
      - "8443:443"
    profiles:
      - fullstack

  dovecot:
    build:
      context: ../tools/Docker/dovecot
    ports:
      - "4190:4190"
    profiles:
      - fullstack
